# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrumchrono < Formula
  desc "ScrumChrono is a terminal UI to aid Scrum meetings."
  homepage "https://github.com/pedrojreis/ScrumChrono"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.3/ScrumChrono_Darwin_arm64.tar.gz"
      sha256 "1a99e2165d344a3bc6a679bb8a50be3f310e416cd8b90e0240156b3995b4ae86"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.3/ScrumChrono_Darwin_x86_64.tar.gz"
      sha256 "407d91dd25d5da4b91c8cf6d6622171e97c852a12420963c43169e9cfb0409cd"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.3/ScrumChrono_Linux_arm64.tar.gz"
      sha256 "b242444905a50c74a0daa3d7d86b1e18125dc01a7cb6597be527da1b8a3f0997"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.3/ScrumChrono_Linux_x86_64.tar.gz"
      sha256 "a82caa8a6867465ad789596aa0ac7755e71465f9a19e6b0d8b7cca1a7b8945a9"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  test do
    system "ScrumChrono --version"
  end
end
