# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scrumchrono < Formula
  desc "ScrumChrono is a terminal UI to aid Scrum meetings."
  homepage "https://github.com/pedrojreis/ScrumChrono"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.1/ScrumChrono_Darwin_arm64.tar.gz"
      sha256 "c176835fcf49b4a3c6ddf5dbca92452bfa68fe1df386e7e3d5251952fff9b726"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.1/ScrumChrono_Darwin_x86_64.tar.gz"
      sha256 "5da363a153d4d3376e8ab8947bc77b091d967b237ee05deff6e21fbe890387bf"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.1/ScrumChrono_Linux_arm64.tar.gz"
      sha256 "53a1650ce8f3949116470e3bf9c6ee038b70a308fd56a21b97381e0b0697e691"

      def install
        bin.install "ScrumChrono"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/pedrojreis/ScrumChrono/releases/download/v0.1.1/ScrumChrono_Linux_x86_64.tar.gz"
      sha256 "4302e3bb3aeca9add80074ebd13157d8dee6986d572fb966fac01a22c255c91b"

      def install
        bin.install "ScrumChrono"
      end
    end
  end

  test do
    system "ScrumChrono --version"
  end
end
